version: "3.8"

services:
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - '61616:61616'
      - '61613:61613'
      - '8161:8161'
    volumes:
      - ./server/activemq/data:/data/activemq

  redis:
    image: redis:7.0.4-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    volumes: 
      - ./server/redis/data:/data